name: Dev Integration Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SOLUTION_NAME: SpecIF_Backend-dev.sln

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/${SOLUTION_NAME}

    - name: Build
      run: dotnet build --no-restore -c Release ./src/${SOLUTION_NAME}


      
