name: Dev Integration Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: MDD4All.SpecIF.Microservice 
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Set integration version from current date
      run: echo "DATE_VERSION=$(date +'%Y.%j')" >> $GITHUB_ENV

    - name: Create version number
      run: echo "VERSION=$(echo $DATE_VERSION.$GITHUB_RUN_NUMBER)" >> $GITHUB_ENV

    - name: Echo version number
      run: echo $VERSION

    - name: Restore dependencies
      run: dotnet restore ./src/${PROJECT_NAME}/${PROJECT_NAME}-dev.csproj

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${VERSION} ./src/${PROJECT_NAME}/${PROJECT_NAME}-dev.csproj
      
