name: Dev Integration Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    env:
      SOLUTION_NAME: SpecIF_Backend-dev.sln 

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: dotnet restore ./src/${{env.SOLUTION_NAME}}

    - name: Build
      run: msbuild ./src/${{env.SOLUTION_NAME}} /p:Configuration=Release 


      
