name: Build and push Docker

on:
  workflow_dispatch:

jobs:
  publish_docker:

    runs-on: ubuntu-latest
    env:
      SOLUTION_NAME: SpecIF_Backend-dev.sln 
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Set integration version from current date
      run: echo "DATE_VERSION=$(date +'%Y.%j')" >> $GITHUB_ENV

    - name: Create version number
      run: echo "VERSION=$(echo $DATE_VERSION.$GITHUB_RUN_NUMBER)" >> $GITHUB_ENV

    - name: Echo version number
      run: echo $VERSION

    - name: Restore dependencies
      run: dotnet restore ./src/${SOLUTION_NAME}

    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${VERSION} ./src/${SOLUTION_NAME}
      
    - name: Publish
      run: dotnet publish -c Release /p:Version=$(VERSION) --runtime linux-x64 ./src/${SOLUTION_NAME}
      
    - name: build Docker
      run: docker build -t ghcr.io/nicholas-mc/${SOLUTION_NAME}:$VERSION .
      
    - name: login Docker
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
     
    
    - name: push Docker
      run: docker push ghcr.io/nicholas-mc/${SOLUTION_NAME}:$VERSION    
     
    
      
      
